# -*- coding: utf-8 -*-
"""User_exapnse_forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8PnIRKtZ4eEg8ISKwMROh4KlWB5Mut_
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("computingvictor/transactions-fraud-datasets")

print("Path to dataset files:", path)

import os
import json
with open(os.path.join(path, 'train_fraud_labels.json'), 'r') as file:
    fraud_labels = json.load(file)

from pyspark.sql import SparkSession

# Initialize Spark session
spark = SparkSession.builder.appName("UserTransaction") \
                    .config("spark.driver.memory","4g").getOrCreate()


# Read CSV files into Spark DataFrames
transactions = spark.read.csv(f"{path}/transactions_data.csv", header=True, inferSchema=True)
cards = spark.read.csv(f"{path}/cards_data.csv", header=True, inferSchema=True)
users = spark.read.csv(f"{path}/users_data.csv", header=True, inferSchema=True)

data = [(trans_id, label) for trans_id, label in fraud_labels["target"].items()]


columns = ["trans_id", "fraud_label"]

# Create PySpark DataFrame
fraud_label_df = spark.createDataFrame(data, columns)

# Show first few rows of each DataFrame
print("Transactions Data:")
transactions.show(5)

print("Cards Data:")
cards.show(5)

print("Users Data:")
users.show(5)

print("Fraud Label:")
fraud_label_df.show(5)

transactions = transactions.join(fraud_label_df, transactions.id == fraud_label_df.trans_id, "inner")

transactions = transactions.drop("id")
transactions.show()

users = users.withColumnRenamed("id","user_id")
cards = cards.withColumnRenamed("id","cards_id")

user_card = users.join(cards,users.user_id == cards.client_id, how="inner").drop("client_id")

user_card.show(5)

user_transactions = user_card.join(transactions, user_card.cards_id == transactions.card_id, how="inner").drop("card_id")
user_transactions.show(5)

user_transactions = user_transactions.withColumnRenamed("id","transaction_id")
user_transactions=user_transactions.drop("client_id")
user_transactions = user_transactions.withColumnRenamed("date","trans_date")
user_transactions = user_transactions.orderBy("user_id","trans_date")
user_transactions.show(5)

from pyspark.sql.functions import col, count, when

null_counts = user_transactions.select([count(when(col(c).isNull(),c)).alias(c) for c in user_transactions.columns])
null_counts.show()

expanse_fore = user_transactions.select("user_id","per_capita_income","yearly_income","total_debt",\
                                        "cards_id","card_type","credit_score","num_credit_cards","trans_date","amount", \
                                        "fraud_label"
                                        )
expanse_fore.show(5)

from pyspark.sql.functions import col, regexp_replace

def replace_dollar_sign(df, column_name):

  return df.withColumn(column_name, regexp_replace(col(column_name),"\\$",""))


expanse_fore = replace_dollar_sign(expanse_fore, "per_capita_income")
expanse_fore = replace_dollar_sign(expanse_fore, "yearly_income")
expanse_fore = replace_dollar_sign(expanse_fore, "total_debt")
expanse_fore = replace_dollar_sign(expanse_fore, "amount")
expanse_fore.show(5)

user_fore = expanse_fore.filter(col("user_id") == 1098)
user_fore.show(5)

from pyspark.sql.functions import asc, desc
from pyspark.sql.functions import to_date, col

user_fore = user_fore.withColumn("per_capita_income",col("per_capita_income").cast("float"))\
                     .withColumn("yearly_income",col("yearly_income").cast("float"))\
                     .withColumn("total_debt",col("total_debt").cast("float"))\
                     .withColumn("amount",col("amount").cast("float"))

def data_preprocessing(df):

  df = df.filter(col("amount")>0)
  df = df.sort(asc("trans_date"))
  df = df.withColumn("trans_only_date",to_date(col("trans_date")))



  return df

user_fore1 = data_preprocessing(user_fore)
user_fore1.show(10)

user_fore1 = user_fore1.filter(col("fraud_label")=="No")
user_fore1.show()

from pyspark.sql.functions import col, sum as spark_sum, to_date, dayofmonth, month, year, dayofweek, lag

user_fore1 = user_fore1.withColumn("trans_date", col("trans_date").cast("timestamp"))
user_fore1 = user_fore1.withColumn("trans_only_date", to_date(col("trans_only_date"), "yyyy-MM-dd"))

daily = user_fore1.groupBy("trans_only_date").agg(spark_sum("amount").alias("daily_amount"))
daily = daily.withColumnRenamed("trans_only_date", "date")

daily = daily.withColumn("day", dayofmonth(col("date")))
daily = daily.withColumn("month", month(col("date")))
daily = daily.withColumn("year", year(col("date")))
daily = daily.withColumn("weekday", dayofweek(col("date")))

daily = daily.orderBy("date")
daily.show(10)

daily.count()

import matplotlib.pyplot as plt

daily_pd = daily.toPandas()

# Create the time series plot
plt.figure(figsize=(10, 6))
plt.plot(daily_pd['date'], daily_pd['daily_amount'])
plt.xlabel('Date')
plt.ylabel('Daily Amount')
plt.title('Time Series Plot of Daily Amount')
plt.grid(True)
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

from pyspark.sql.window import Window
from pyspark.sql.functions import col, sin, cos, lit

windowSpec = Window.orderBy("date")
daily = daily.withColumn("lag_1", lag("daily_amount",1).over(windowSpec))
daily = daily.withColumn("lag_7", lag("daily_amount",7).over(windowSpec))
daily = daily.withColumn("lag_14", lag("daily_amount",14).over(windowSpec))
daily = daily.withColumn("lag_21", lag("daily_amount",21).over(windowSpec))

daily = daily.withColumn("sin_month", sin(2*lit(3.141)*col("month") /12))
daily = daily.withColumn("cos_month", cos(2*lit(3.141)*col("month") /12))
daily = daily.withColumn("sin_day", sin(2*lit(3.141)*col("weekday") /7))
daily = daily.withColumn("cos_day", cos(2*lit(3.141)*col("weekday") /7))

daily = daily.drop("month","weekday")
daily.show()

daily = daily.na.drop()

daily_pd = daily.toPandas()
daily_pd.head()

#daily = daily.drop("day")
daily.show()

daily_pd = daily_pd.set_index("date")
daily_pd = daily_pd.sort_index()
split_index = int(len(daily_pd)*0.8)
split_date = daily_pd.index[split_index]

train = daily_pd.loc[:split_date].iloc[:-1]  # Exclude the split date from training
test = daily_pd.loc[split_date:]

from sklearn.preprocessing import StandardScaler
import pandas as pd

Features = ["year", "day", "lag_1", "lag_7", "lag_14","lag_21","sin_month","cos_month","sin_day","cos_day"]
Target = "daily_amount"

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_trainval = train[Features]
y_trainval = train[Target]

X_test = test[Features]
y_test = test[Target]

X_trainval_scaled = scaler_X.fit_transform(X_trainval)
y_trainval_scaled = scaler_y.fit_transform(y_trainval.values.reshape(-1, 1))

X_trainval = pd.DataFrame(X_trainval_scaled, columns=X_trainval.columns, index=X_trainval.index)
y_trainval = pd.DataFrame(y_trainval_scaled, columns=[Target], index=y_trainval.index)

X_test_scaled = scaler_X.transform(X_test)
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1))

X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
y_test = pd.DataFrame(y_test_scaled, columns=[Target], index=y_test.index)

import numpy as np
import xgboost as xgb
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error

# Define your features and target


# Define the hyperparameter grid
param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.8, 1.0]
}

# Set up time series cross-validation.
# Adjust n_splits, test_size, and gap as needed.
tss = TimeSeriesSplit(n_splits=5, test_size=365, gap=24)

results = []

# Iterate over all combinations in the grid.
for max_depth in param_grid['max_depth']:
    for learning_rate in param_grid['learning_rate']:
        for subsample in param_grid['subsample']:
            rmses = []
            # Perform time series CV for the current hyperparameter combination.
            for train_index, val_index in tss.split(X_trainval):
                # Split the training set into a smaller train and validation based on indices.
                X_train_cv, X_val = X_trainval.iloc[train_index], X_trainval.iloc[val_index]
                y_train_cv, y_val = y_trainval.iloc[train_index], y_trainval.iloc[val_index]


                # Create the XGBoost regressor with the current hyperparameters.
                reg = xgb.XGBRegressor(
                    base_score=0.5,
                    booster='gbtree',
                    n_estimators=1000,
                    early_stopping_rounds=50,
                    objective='reg:squarederror',  # updated objective for regression
                    max_depth=max_depth,
                    learning_rate=learning_rate,
                    subsample=subsample,
                    random_state=42
                )

                # Fit the model, using only the validation set for early stopping.
                reg.fit(X_train_cv, y_train_cv, eval_set=[(X_val, y_val)], verbose=False)

                # Predict and calculate RMSE for the fold.
                y_pred = reg.predict(X_val)
                rmse = np.sqrt(mean_squared_error(y_val, y_pred))
                rmses.append(rmse)

            # Calculate the average RMSE for the current hyperparameter combination.
            avg_rmse = np.mean(rmses)
            results.append({
                'max_depth': max_depth,
                'learning_rate': learning_rate,
                'subsample': subsample,
                'rmse': avg_rmse
            })
            print(f"Params: max_depth={max_depth}, learning_rate={learning_rate}, subsample={subsample} => RMSE: {avg_rmse:.4f}")

# Determine the best hyperparameter combination (lowest average RMSE).
best_params = min(results, key=lambda x: x['rmse'])
print("\nBest hyperparameters:", best_params)


# Now best_reg is your final model trained on the complete training set.

best_reg = xgb.XGBRegressor(
    base_score=0.5,
    booster='gbtree',
    n_estimators=1000,
    objective='reg:squarederror',
    max_depth=best_params['max_depth'],
    learning_rate=best_params['learning_rate'],
    subsample=best_params['subsample'],
    random_state=42
)


best_reg.fit(X_trainval,y_trainval);
y_pred_val = best_reg.predict(X_test);


y_pred_original = scaler_y.inverse_transform(y_pred_val.reshape(-1, 1))
y_test_original = scaler_y.inverse_transform(y_test.values.reshape(-1, 1))

y_pred = pd.DataFrame(y_pred_original, columns=[Target], index=y_test.index)

y_train_pred = best_reg.predict(X_trainval)
y_train_original = scaler_y.inverse_transform(y_trainval.values.reshape(-1, 1))  # Convert scaled back to original

# Plot actual vs predicted for the test set
plt.figure(figsize=(12, 6))
plt.plot(y_trainval.index, y_trainval.values.reshape(-1, 1), label="Actual Train Values")  # Removed label from reshape and put in plot
plt.plot(y_trainval.index, y_train_pred, label="Predicted Values", linestyle='--', color='red')
plt.xlabel("Time")
plt.ylabel("Daily Amount")
plt.title("Actual vs Predicted Daily Amount on Train Set")
plt.legend()
plt.show()

import matplotlib.pyplot as plt



# Plot actual vs predicted for the test set
plt.figure(figsize=(12, 6))
plt.plot(y_test.index, y_test_original, label="Actual Test Values")
plt.plot(y_test.index, y_pred_original, label="Predicted Values", linestyle='--', color='red')
plt.xlabel("Time")
plt.ylabel("Daily Amount")
plt.title("Actual vs Predicted Daily Amount on Test Set")
plt.legend()
plt.show()

from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test_original, y_pred_original)
print("RMSE:", np.sqrt(rmse))

